name: Deploy React App to S3

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/portafolio:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Cambia a la región de tu bucket

      - name: Download Docker Image and extract files
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/portafolio:latest
          docker create --name app-container ${{ secrets.DOCKERHUB_USERNAME }}/portafolio:latest
          docker cp app-container:/usr/share/nginx/html ./build
          docker rm app-container

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.AWS_BUCKET_NAME }} --delete